name: Purge old sessions

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run purge
      env:
        CI: true
